opt_in_rules:
  - array_init
  - attributes
  - closing_brace
  - closure_end_indentation
  - closure_spacing
  - colon
  - comma
  - compiler_protocol_init
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - control_statement
  - cyclomatic_complexity
  - discarded_notification_center_observer
  - discouraged_direct_init
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - explicit_enum_raw_value
  - explicit_init
  - explicit_top_level_acl
  - no_extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_length
  - first_where
  - for_where
  - force_cast
  - force_try
  - function_body_length
  - function_parameter_count
  - generic_type_name
  - identifier_name
  - implicit_getter
  - implicit_return
  - implicitly_unwrapped_optional
  - is_disjoint
  - joined_default_parameter
  - leading_whitespace
  - let_var_whitespace
  - line_length
  - literal_expression_end_indentation
  - mark
  - multiline_arguments
  - multiline_parameters
  - multiple_closures_with_trailing_closure
  - nesting
  - nimble_operator
  - number_separator
  - object_literal
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_over_fileprivate
  - private_unit_test
  - prohibited_super_call
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_void_return
  - return_arrow_whitespace
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - statement_position
  - strict_fileprivate
  - switch_case_alignment
  - switch_case_on_newline
  - syntactic_sugar
  - trailing_closure
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_name
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unused_closure_parameter
  - unused_enumerated
  - unused_optional_binding
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - void_return
  - weak_delegate
  - xctfail_message

disabled_rules:
  - redundant_string_enum_value
  - superfluous_disable_command
  - extension_access_modifier
  - force_unwrapping
  - todo
  - shorthand_operator
  - type_body_length
  - large_tuple
  - no_grouping_extension
  - explicit_type_interface

included:
  - Sources
  - Tests

excluded:
  - Tests/LinuxMain.swift
  - Tests/*/XCTestManifests.swift

file_header:
  required_pattern: |
                    \/\/ This file is part of the Loobee package\.
                    \/\/
                    \/\/ \(c\) Andrey Savitsky <contact@qroc\.pro>
                    \/\/
                    \/\/ For the full copyright and license information, please view the LICENSE
                    \/\/ file that was distributed with this source code\.

file_length:
  ignore_comment_only_lines: true

identifier_name:
  min_length: 0
  validates_start_with_lowercase: true

line_length: 120

number_separator:
  minimum_length: 5

trailing_comma:
  mandatory_comma: true

