language: swift

matrix:
  include:
    - os: linux
      dist: trusty
      language: generic
      sudo: required
      env:
        - BUILD_LINK=https://swift.org/builds/swift-4.2-convergence/ubuntu1404/swift-4.2-CONVERGENCE/swift-4.2-CONVERGENCE-ubuntu14.04.tar.gz

    - os: osx
      osx_image: xcode9.4
      env:
        - BUILD_LINK=https://swift.org/builds/swift-4.2-convergence/xcode/swift-4.2-CONVERGENCE/swift-4.2-CONVERGENCE-osx.pkg

before_install:
  - sudo /bin/bash scripts/travis-deps.sh
  - chmod u+x scripts/travis-swift.sh
  - . scripts/travis-swift.sh

before_script:
  - clang --version
  - swift --version

script:
  - make

