language: swift

matrix:
  include:
    - os: linux
      dist: trusty
      language: generic
      sudo: required
      env:
        - CLANG_VERSION=4.2
        - BUILD_LINK=https://swift.org/builds/development/ubuntu1404/swift-DEVELOPMENT-SNAPSHOT-2018-08-10-a/swift-DEVELOPMENT-SNAPSHOT-2018-08-10-a-ubuntu14.04.tar.gz

    - os: osx
      osx_image: xcode9.4
      env:
        - BUILD_LINK=https://swift.org/builds/swift-4.2-branch/xcode/swift-4.2-DEVELOPMENT-SNAPSHOT-2018-08-10-a/swift-4.2-DEVELOPMENT-SNAPSHOT-2018-08-10-a-osx.pkg

before_install:
  - sudo /bin/bash scripts/travis-clang.sh
  - chmod u+x scripts/travis-swift.sh
  - . scripts/travis-swift.sh

before_script:
  - clang --version
  - swift --version

script:
  - make

